name: Simple Test Workflow

on:
  # Manual trigger
  workflow_dispatch:
  # Push to any branch
  push:
    branches:
      - '**'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simple test step
        run: |
          echo "Hello from GitHub Actions!"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow file: ${{ github.workflow }}"
          echo "Current branch: ${{ github.ref }}"
          ls -la
